openapi: 3.0.0
info:
  title: Api for getting github repositories of specified user
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Local environment url
paths:
  /repositories/{userName}:
    get:
      summary: Returns a list of user's repositories
      parameters:
        - name: userName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of user repositories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Repository'
        '404':
          description: An error if specified user is not found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: An error message of internal server error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiError'
components:
  schemas:
    ApiError:
      type: object
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
    Branch:
      type: object
      properties:
        branchName:
          type: string
        commitSha:
          type: string
    Repository:
      type: object
      properties:
        name:
          type: string
        ownerLogin:
          type: string
        branches:
          type: array
          items:
            $ref: '#/components/schemas/Branch'
